### ISSUE TITLE
Please create a Dockerfile so we can deploy to DigitalOcean / Render.com / AWS Container services

### ISSUE THREAD

**Issue by zackees** [Openpanel-dev/openpanel#10]
This will give one click app creation

**Comment by lindesvard** [comment]
Self hosting is next up on the agenda.

**Comment by jjaimealeman** [comment]
> Self hosting is next up on the agenda.

Looking forward to this.

I'm a long time DigitalOcean user and recently switched from CapRover to Coolify https://coolify.io/

Would love to give the `self-host` route a shot when it's ready 👍🏽

**Comment by lindesvard** [comment]
<img width="384" alt="image" src="https://github.com/Openpanel-dev/openpanel/assets/1987198/8b1ddb2b-ce8d-45bf-aac7-9c2b4f853428">

Work in progress now

**Comment by lindesvard** [comment]
Well this can be closed now https://docs.openpanel.dev/docs/self-hosting
