### ISSUE TITLE
Proxying broken/docs out of date

### ISSUE THREAD

**Issue by kennethlynne** [Openpanel-dev/openpanel#102]
Setting up proxying according to documentation seems broken.

Types are incorrect and implementation is broken.

Following:
https://openpanel.dev/docs/sdks/nextjs#proxy-events

Yields:
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/4112373a-c0fa-4130-83da-191e0ebf63c3">

Then adding an empty object satisfies the types.
However no events except for the "session started" are visible in the console.

Note: Removing `apiUrl="/api/op"` everything works as expected so it seems it is something with the docs/proxying code

**Comment by kennethlynne** [comment]
Related to https://github.com/Openpanel-dev/openpanel/issues/100 - but this tracks the incorrect types

**Comment by lindesvard** [comment]
So I noticed I missed making the options optional for some reason. So for now just do `export const POST = createNextRouteHandler({});`

But would like to see the path to this file and then also your `<OpenPanelComponent />`.

**Comment by kennethlynne** [comment]
`app/api/[...op]/route.ts`
```
import { createNextRouteHandler } from '@openpanel/nextjs/server';

export const POST = createNextRouteHandler({});
```

```
      <OpenPanelComponent
        clientId={env.NEXT_PUBLIC_OPENPANEL_CLIENT_ID}
        apiUrl="/api/op"
        trackScreenViews={true}
        trackOutgoingLinks={true}
        globalProperties={{
          appVersion: env.NEXT_PUBLIC_APP_VERSION,
          environment: env.NEXT_PUBLIC_APP_ENV,
        }}
      />
```

**Comment by lindesvard** [comment]
Hmm this looks correct. What error do you get in the networks tab? This setup works fine for me just fine.

![image](https://github.com/user-attachments/assets/a2c13ec0-f71c-4182-91b8-334825b3b477)

**Comment by kennethlynne** [comment]
Sorry for the inconvenience, I got it to work now. It might have been CORS issues or something else entirely, but I did a sweep over the entire setup and now it works.
