### ISSUE TITLE
Dart SDK

### ISSUE THREAD

**Issue by chillbrodev** [Openpanel-dev/openpanel#13]
Hello, love the idea of this product. What is the likelihood of adding a Dart SDK? This would be great to have for integrations into Flutter apps.

**Comment by lindesvard** [comment]
@stevenosse has created a flutter SDK - https://pub.dev/packages/openpanel_flutter

**Comment by Blankeos** [comment]
I feel like it should be on the docs even if third-party https://openpanel.dev/docs/sdks 🤞

**Comment by lindesvard** [comment]
https://github.com/stevenosse/openpanel_flutter/issues/2
