### ISSUE TITLE
Feedback for “API”

### ISSUE THREAD

**Issue by tmdevde** [Openpanel-dev/openpanel#16]
Hi there,

I really love Openpanel. We have a lot of Laravel projects, and a couple of days ago I thought there was an integration for that on the main site. Unfortunately, it is critical for us to send events and stats via Laravel (PHP) since some applications don't have a frontend.

What is the current state of a PHP (Laravel) SDK? Did I miss something?

Thank you!

**Comment by lindesvard** [comment]
Hey! Glad you like it! 

Thanks to @tbleckert we have one

https://github.com/tbleckert/openpanel-laravel
