### ISSUE TITLE
UTM  source not working?

### ISSUE THREAD

**Issue by AlbertoMontalesi** [Openpanel-dev/openpanel#17]
First of all, awesome project. I'm really liking it so far.

I'm trying to understand if there's an issue with UTM tags because i have a link like the following `https://mysite.com?utm_source=reddit&utm_medium=cpc&utm_campaign=c_1` and i don't see anything coming up in the OpenPanel dashboard when i visit that url.  Everything else seems to be working correctly.

**Comment by AlbertoMontalesi** [comment]
I've seen your test come up and i've tested it again on a different browser. It's working fine. i think it might have been my ad blocker. I'll close the issue.

**Comment by lindesvard** [comment]
Hey @AlbertoMontalesi 

I believe that utm tags are working, but might not work as you would expect. This is how it works:

If a session is already started and you then add utm tags to your link, then the session will not get these utm tags. So you would need to visit your site with utm tags when a session is created.

You could try open up a new browser (if you use firefox, then open chrome instead) and see if the utm source appears. I just tried with `utm_source=github_issue_source` and looks like it got registered.
