### ISSUE TITLE
Python SDK

### ISSUE THREAD

**Issue by leikoilja** [Openpanel-dev/openpanel#18]
Hey guys.

Happy to see the project take off and having traction.
Is there any python SDK available? Would be great to integrate with django/flask web-servers

**Comment by lindesvard** [comment]
Thanks for tracking the issue here as well 🙏

**Comment by SyedMuzamilM** [comment]
Hey @lindesvard I would like to build this sdk. Let me know should I put it in the sdk packages.

**Comment by lindesvard** [comment]
Hey @SyedMuzamilM and thanks for you want to help out. So I have already put in some work on this and it can see it here https://github.com/Openpanel-dev/python-sdk

But, its not a package yet and the code needs to be reviewed and tested more. If you're up for the task I would be grateful.

**Comment by SyedMuzamilM** [comment]
Oh. Great will make a PR there. Will work on it tomorrow. I tried to add the python-sdk in the packages/sdks and made a Draft PR. 

Will start on the other repo tomorrow then. Thanks

**Comment by lindesvard** [comment]
Have published the SDK https://pypi.org/project/openpanel/

Thanks once again @SyedMuzamilM for all your help 🫶

**Comment by SyedMuzamilM** [comment]
Awesome. 

I am really interested in this projects would be making some more contributions. But for now I don’t have enough time. 

Will be working on more issues after some days. 

Thanks.

**Comment by leikoilja** [comment]
Great job, thank you @lindesvard 🙌
