### ISSUE TITLE
"Your dashboards" sidebar section styles for longer names are broken

### ISSUE THREAD

**Issue by Igloczek** [Openpanel-dev/openpanel#23]
How it looks right now:
![CleanShot 2024-05-28 at 11 14 40](https://github.com/Openpanel-dev/openpanel/assets/5119280/6b805b45-eaab-4b4e-835f-26ec86db88fc)

How I think it should looks like:
![CleanShot 2024-05-28 at 11 14 24](https://github.com/Openpanel-dev/openpanel/assets/5119280/4493d623-8f10-485e-888f-a65ff46da581)

In my opinion, the project name in this place is simply not necessary, because from what I see there in no way to list dashboards from multiple projects, so simply removing it is the easiest way to fix the problem of funky look.

**Comment by lindesvard** [comment]
Thanks @Igloczek, fixed now

<img width="299" alt="image" src="https://github.com/Openpanel-dev/openpanel/assets/1987198/ea1ca01a-e6f8-42e2-9ddc-6ad005aff041">
