### ISSUE TITLE
Bug: Click pencil icon not editing report name

### ISSUE THREAD

**Issue by AlbertoMontalesi** [Openpanel-dev/openpanel#25]
<img width="311" alt="image" src="https://github.com/Openpanel-dev/openpanel/assets/23130353/47a4504e-d912-4444-a90f-70689f0d12f6">

**Comment by lindesvard** [comment]
To be honest. I have completely forgotten about this little pencil! Will add the functionality for sure

**Comment by Pranav2612000** [comment]
Are you open to contributors? Would love to work on this issue

**Comment by lindesvard** [comment]
@Pranav2612000 yes but this issues is not a great start since I need to restructure how the chart editor use redux.

Want to redo this with another state library.
