### ISSUE TITLE
Mobile SDK Support

### ISSUE THREAD

**Issue by phpmaple** [Openpanel-dev/openpanel#26]
like flutter or Native iOS/Android

**Comment by lindesvard** [comment]
#13 for flutter but haven't had any time for native iOS/android sdk sadly. 

Looking for contributions here 😅

**Comment by lindesvard** [comment]
**Swift SDK** https://github.com/Openpanel-dev/swift-sdk _(v1.0.0 is released)_
**Kotlin SDK** https://github.com/Openpanel-dev/kotlin-sdk _(soon done)_

Will close this issue and will also post when the kotlin sdk is completely done
