### ISSUE TITLE
Bug: Renaming organization breaks the project picker

### ISSUE THREAD

**Issue by Than-DE** [Openpanel-dev/openpanel#30]
https://github.com/Openpanel-dev/openpanel/assets/74593656/ecef74a0-e0cd-49d1-84a1-f98b31306f58

Hi,

I renamed my organization a while ago. I assume this broke the project picker for me. To debug this, it might be helpful to look at the URL. 

I don't remember exactly but I think the previous organization name was `zenquiz`

**Comment by lindesvard** [comment]
Ops! Will look into this

**Comment by lindesvard** [comment]
I have looked into this and not sure how this happen tbh. Changing name should only change the name and nothing else. I have disabled org name change for now and will dig into this more later. If you have more info please fill free to re-open this issue.
