### ISSUE TITLE
Add operators in filters

### ISSUE THREAD

**Issue by Than-DE** [Openpanel-dev/openpanel#31]
Hi,

A feature that would really elevate the analytics capabilities of openpanel would be operators for property filters.

![CleanShot 2024-06-07 at 16 11 36@2x](https://github.com/Openpanel-dev/openpanel/assets/74593656/11f20c80-f91d-4d5b-9792-9e9fdaeffa63)

For example, my page has a /blog route with different articles underneath. I would like to filter by all blog paths, so I would filter by "path **contains** 'blog'"

Some operators that come to my head right away are
- is (exists already)
- is not
- contains
- contains not
- starts with
- ends with

This is probably quite a big endeavour because some properties might need different operators. For example `created_at` would only really need "is" and "is not" - but could use different operators like "before" and "after".

Would love to work on this myself some time but I don't have a local environment running. Could also help with conceptualising this idea.

**Comment by lindesvard** [comment]
We have a few operators but have not added them for the overview yet. 

Great suggestion!

**Comment by lindesvard** [comment]
https://github.com/user-attachments/assets/ce835d22-d802-4ccc-8f74-e8689fc4dba7

Sorry for the long wait. This coming tomorrow 🫶

**Comment by Than-DE** [comment]
Insane. Looks great.

**Comment by lindesvard** [comment]
Fixed and deployed
