### ISSUE TITLE
Search index missing

### ISSUE THREAD

**Issue by pushcx** [Openpanel-dev/openpanel#32]
![2024-06-07_13-02](https://github.com/Openpanel-dev/openpanel/assets/6262/d6505f40-e618-4d58-9664-c7882a75bf59)

There's a 404 for https://docs.openpanel.dev/_next/static/chunks/nextra-data-en.json in the dev tools console.

(And to the search - it would be great to see a doc about ensuring GDPR compliance, a claim made on the homepage.)

**Comment by lindesvard** [comment]
Thanks, will improve docs a lot soon 🤞
