### ISSUE TITLE
Issue in reports

### ISSUE THREAD

**Issue by AlbertoMontalesi** [Openpanel-dev/openpanel#33]
I've created a report with  two events and encountered a couple of issues

- both A and B use the same event but I've applied filtered based on path, this causes the chart to only show results for event B
- then I tried to give a specific name to each of them which worked, now I have one line for A and one for B, the problem is that on save, it doesn't stick. when I come back it's back to both of them having no "name" and only one line showing.

Let me know if you need more infos

**Comment by lindesvard** [comment]
Thanks! I know exactly what's going on! Will fix this 🤞

**Comment by lindesvard** [comment]
Should be fixed now!
