### ISSUE TITLE
Differences with plausible

### ISSUE THREAD

**Issue by afanjul** [Openpanel-dev/openpanel#34]
Hi @lindesvard I've discovered your project swimming in github (congratulations), I'm using plausible right now, and looking into your demo, it seems almost the same (at least regarding UI). I read through your web text that you like the plausible simplicity, but from the user point of view, the first time we look at to your product is almost a fork. 

May you please elaborate the differences of your product with plausible product in a simple list? Also, as a recommendation I would add this list to your product web. 
thanks

P.S: I also let this request as a issue so anybody could find the differences right away in case they think the same

**Comment by lindesvard** [comment]
A "fork" is quite a statement imo.  Check out the source code and look for one line that is the same.

I love plausible and wanted a similar feeling (for my overview) as their overview page. Can name a few projects that has the same setup

- simple analytics
- Umami
- pirsch analytics
- and many many more

---

Differences:

- The big difference is that I'm actually building an open source alternative to mixpanel where you can visualize your data.
- Access all your users session
- access all your events and what user is associated with the event
- Get retention information about your users
- Great react-native support
- Export api where you can get chart data and just plain events

Just to name a few.

**Comment by leikoilja** [comment]
@lindesvard , react-native support is HUGE! thanks for the project, looking forward it growing 🚀

**Comment by afanjul** [comment]
Thanks for your comments @lindesvard I will give you feedback as soon as we have installation docs and can try it in our server...
