### ISSUE TITLE
Set profile information with the API

### ISSUE THREAD

**Issue by Julienh** [Openpanel-dev/openpanel#37]
How to set profile data with like with the [script tag](https://docs.openpanel.dev/docs/script#additional-data) but with the [API](https://docs.openpanel.dev/docs/api)?

Additional question, did you planed to add a Companies to group Profile user by companies please?

Thank you.

**Comment by lindesvard** [comment]
Below should do the trick. All properties are optional except `profileId`. I have thought about adding groups/segments to profiles but will be some time before adding this feature.

```
curl 'https://api.openpanel.dev/profile' \
  -H 'content-type: application/json' \
  -H 'openpanel-client-id: CLIENT_ID' \
  -H 'openpanel-client-secret: CLIENT_SECRET' \
  --data-raw '{"profileId":"the_profile_id","firstName":"Joe","lastName":"Doe","email":"joe@doe.com","avatar":"https://example.com/avatar.jpg","properties":{"foo":"Bar"}}'
```

**Comment by Julienh** [comment]
It is working well, thank you!

Groups (companies) and Segments would be great!
