### ISSUE TITLE
Feedback for “Next.js”

### ISSUE THREAD

**Issue by hootan-nikbakht** [Openpanel-dev/openpanel#39]
Hey I am building into openpanel nextjs library and I can't get trackEvent('my_event', { foo: 'bar' }); to work. 

I keep getting "window.op is not a function"

**Comment by lindesvard** [comment]
I would assume you try to use `trackEvent` inside a server component. 

Can you give this a try an come back if its working https://docs.openpanel.dev/docs/nextjs#track-server-events

Re-open if its still an issue
