### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by Nexus-Security** [Openpanel-dev/openpanel#40]
i am having this error that keep appearing in the console after i add openpanel with GTM

<script src="https://openpanel.dev/op.js" defer async></script>
<script>
window.op = window.op || function () {
  for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }
  (window.op.q = window.op.q || []).push(args);
};
window.op('ctor', {
  clientId: '1111111111111111111',
  trackScreenViews: true,
  trackOutgoingLinks: true,
  trackAttributes: true
});
</script>

site : https://nexus-security.github.io

VM113 op.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'bind')
    at r.op (VM113 op.js:1:4330)
    at <anonymous>:1:147
    at gtm.js?id=GTM-5X67X4Q4:445:427
    at HTMLScriptElement.<anonymous> (gtm.js?id=GTM-5X67X4Q4:446:131)

**Comment by lindesvard** [comment]
Hey! 

Can you try to swap places for the `window.op` and the `src` tag? Like below

```
<script>
  window.op =
    window.op ||
    function (...args) {
      (window.op.q = window.op.q || []).push(args);
    };
  window.op('ctor', {
    clientId: 'YOUR_CLIENT_ID',
    trackScreenViews: true,
    trackOutgoingLinks: true,
    trackAttributes: true,
  });
</script>
<script src="https://openpanel.dev/op.js" defer async></script>
```

**Comment by Nexus-Security** [comment]
thanks  [lindesvard](https://github.com/lindesvard) it worked perfectly
