### ISSUE TITLE
Local setup getting failed 

### ISSUE THREAD

**Issue by tarunkumarmetaforms** [Openpanel-dev/openpanel#45]
![Screenshot 2024-08-03 at 7 21 33 PM](https://github.com/user-attachments/assets/a3d0cc5b-3420-4d4e-91e7-93e1ad60439d)

while added the env  still getting the error of 

http://localhost:3000/undefined/trpc/onboarding.skipOnboardingCheck?input=%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D

debuged for a long time not able to find why it is happeing

**Comment by tarunkumarmetaforms** [comment]
my .env.local include this 

REDIS_URL=
DATABASE_URL=
DATABASE_URL_DIRECT=
CLERK_SIGNING_SECRET="/liwaHz2Shakb"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

**Comment by tarunkumarmetaforms** [comment]
![Screenshot 2024-08-03 at 7 33 17 PM](https://github.com/user-attachments/assets/5a6443d3-5bee-4a5a-8fef-60e9a90ca617)


also my event's are also getting failed

**Comment by lindesvard** [comment]
You are missing the `NEXT_PUBLIC_API_URL` https://github.com/Openpanel-dev/openpanel/blob/main/apps/dashboard/src/app/providers.tsx#L38

```
REDIS_URL="redis://127.0.0.1:6379"
DATABASE_URL="postgresql://local@localhost:5432/mixan?schema=public"
DATABASE_URL_DIRECT="postgresql://local@localhost:5432/mixan?schema=public"
CLICKHOUSE_URL="http://localhost:8123"
CLICKHOUSE_DB="openpanel"
CLICKHOUSE_USER="default"

WORKER_PORT=9999
API_PORT=3333
NEXT_PUBLIC_DASHBOARD_URL="http://localhost:3000"
NEXT_PUBLIC_API_URL="http://localhost:3333"

# Clerk
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=
CLERK_SIGNING_SECRET=
NEXT_PUBLIC_CLERK_SIGN_IN_URL="/login"
NEXT_PUBLIC_CLERK_SIGN_UP_URL="/register"
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL="/"
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL="/"
```

Regarding Clerk webhooks, hard to say whats failing without any info.

**Comment by lindesvard** [comment]
Closing this now, re-open if you still have issues
