### ISSUE TITLE
Haunted event in report events picker

### ISSUE THREAD

**Issue by Igloczek** [Openpanel-dev/openpanel#47]
https://github.com/user-attachments/assets/c6d0776b-b454-4671-a420-e5a74e9d11c8

1. It removes the wrong event when trying to remove the "haunted" event, then the whole UI becomes unresponsive.
3. If I remove some other "not-haunted" event, the "haunted" event UI becomes unresponsive, but when I close the window without saving changes and reopen it without page refresh, the "haunted" event got removed anyway.

I kinda don't know how to describe it more precisely, so "haunted" seems to be the most accurate name I can come with 😅

**Comment by Igloczek** [comment]
and there is more weirdness going on there 😬 

https://github.com/user-attachments/assets/4dcc0281-868c-4457-bd38-2adc5a3abb0c

**Comment by lindesvard** [comment]
Will look into it 🙏

**Comment by lindesvard** [comment]
I know what the issue is and will try to fix it tonight (otherwise a fix will come out tomorrow)

**Comment by lindesvard** [comment]
Should be solved now

**Comment by Igloczek** [comment]
Thanks Carl, made a few new dashboards, edited some existing one, no haunted events found :bow:
