### ISSUE TITLE
Error Loading Resources - 401 Unauthorized and 404 Not Found

### ISSUE THREAD

**Issue by kamilczujowski** [Openpanel-dev/openpanel#54]
We are encountering issues related to loading resources in our current implementation. The errors are primarily 401 Unauthorized and 404 Not Found, as well as Source Map loading errors in Safari

Error Details:

	1.	401 Unauthorized:
	•	URL: https://api.openpanel.dev/track
	•	Issue: The server responded with a status of 401, which indicates an unauthorized request.

	2.	404 Not Found:
	•	URLs:
	•	https://openpanel.dev/tracker.global.js.map
	•	https://openpanel.dev/tracker.global.js.map
	•	Issue: The server responded with a status of 404, which indicates the requested resource could not be found.

	3.	Source Map Loading Errors:
	•	Error: Source Map-Ladefehler
	•	URLs: Same as above, related to the 404 errors for source maps.

Embed Code Snippet:
```
<Script id="openpanel-init" strategy="afterInteractive">
  {`
    window.op = window.op||function(...args){(window.op.q=window.op.q||[]).push(args);};
    window.op('init', {
      clientId: '<client-id>',
      trackScreenViews: true,
      trackOutgoingLinks: true,
      trackAttributes: true,
    });
  `}
</Script>
<Script 
  src="https://openpanel.dev/op1.js" 
  strategy="afterInteractive"
/>
```
<img width="1669" alt="Bildschirmfoto 2024-09-02 um 17 36 21" src="https://github.com/user-attachments/assets/29ffb00d-5003-44a8-b610-2457a384019f">

**Comment by lindesvard** [comment]
Hey and thanks for reporting.

401 indicates something is wrong with you `client_id` or your cors settings. If you're sure the `client_id` is correct you probably have issues with the cors (`Domains` in the picture below) options. 

I have also made a change to the error response that will give you a hint what is wrong (will not deploy this tonight tho)

<img width="545" alt="image" src="https://github.com/user-attachments/assets/77d69893-328d-4df6-9e5f-8f97caf93414">

Regarding sourcemaps, will remove them completely (but nothing that causing the 401)

**Comment by kamilczujowski** [comment]
Hey, thanks for the quick feedback – I really appreciate it!

You were right. There was an issue with the domain. I thought that adding only the “non-www” domain would work like a wildcard. I added the “www” version as well, so now both domains (non-www and www) are included, and the 401 issue is resolved.

Thanks for removing the sourcemaps!
