### ISSUE TITLE
Run ClickHouse migrations on startup / via CLI

### ISSUE THREAD

**Issue by bohdan-shulha** [Openpanel-dev/openpanel#56]
Hey. :)

I'm trying to integrate OpenPanel as a 1-Click App template and I see that the clickhouse migrations are being executed as a one-off process.

While it seems to work, I find it not very intuitive.

How about adding a CLI to run these migrations, likewise app already do with Prisma?

I'd be happy to commit the change to get this feature earlier. :)

**Comment by lindesvard** [comment]
fixed: https://github.com/Openpanel-dev/openpanel/commit/b44f1958a277b8dd6b97c6651da9138bb869f789

**Comment by bohdan-shulha** [comment]
Thanks a lot, I was able to test it locally and will be deploying a live instance next week. :)
