### ISSUE TITLE
QA: Funnels - does it exist ?

### ISSUE THREAD

**Issue by orenmizr** [Openpanel-dev/openpanel#60]
i could not find anything of the docs site. are you able to fedine funnels in this version ? 
are you able to set goals and see how many users converted ? 

i logged in the dashboard but i have not data to verify anything.  just want to understand the current state of the app.

**Comment by lindesvard** [comment]
Funnels and other types of information is up to each user to create. So basically you do the following.

Create a dashboard and then you create a new reports. Inside their you can choose what type of chart you want.

![image](https://github.com/user-attachments/assets/d18fbec4-6958-4fd4-bdce-b18eb0ef5ce6)
