### ISSUE TITLE
QA: How does profiles work?

### ISSUE THREAD

**Issue by perostlin** [Openpanel-dev/openpanel#63]
Hello,

I have currently started to look into OpenPanel and so far it's really nice and easy to use, **great work!**

I have a question regarding profiles.

I have setup a SvelteKit app with OpenPanel and managed to get everything working, both client and server-side.
But I'm getting multiple profiles, see image below, even though it's the same user.
So I'm wondering how profiles work? 
I'm unable to find documentation around this.

What I can see when tracking is that when I track from the **server** I get one profile and when I track from the client I get another and vice-versa.

I do see that there is a "Power Users" tab where the user shows up once.

Profiles
![image](https://github.com/user-attachments/assets/8a2be522-cf01-41e2-b56a-378e5eed024e)

Power Users
![image](https://github.com/user-attachments/assets/436059ef-2499-44ce-aae4-57cc7d07051d)

**Comment by lindesvard** [comment]
Hey!

And glad you liking it so far! When I optimized the profiles tables I screwed up the merging process. 

So you will se duplicated profiles until I have fixed this. Hoping to get it solved by tomorrow or thursday!

**Comment by lindesvard** [comment]
Fixed!

**Comment by perostlin** [comment]
Works now, thank you!
