### ISSUE TITLE
export api pagination bug?

### ISSUE THREAD

**Issue by jenpnd** [Openpanel-dev/openpanel#64]
I believe there is a bug on the Export API pagination.

This is the initial meta response on initial API call.

```
"meta": {
        "count": 50,
        "totalCount": 5294,
        "pages": 106,
        "current": 1
    },
```

Changing the param to `page = 2`, it returns this:

```
"meta": {
        "count": 23,
        "totalCount": 1516,
        "pages": 31,
        "current": 2
    },
```

`page = 3` returns:

```
"meta": {
        "count": 0,
        "totalCount": 1516,
        "pages": 31,
        "current": 3
    },
```

Documentation does not seem to be updated:
https://docs.openpanel.dev/docs/sdks/export 

<img width="852" alt="image" src="https://github.com/user-attachments/assets/ec046332-e77b-4c4c-a95d-ffe933521684">

**Comment by lindesvard** [comment]
I cache the `totalCount` and the approach I do it with is less then optimal. Will remove the cache temporary. 

As for the docs, will try to fill it out 🙏

**Comment by lindesvard** [comment]
hopefully fixed here https://github.com/Openpanel-dev/openpanel/commit/c4be1dc05d3c2776e6eac8d36519d0be5f7d438b
