### ISSUE TITLE
Feedback about "Script tag" (identify method)

### ISSUE THREAD

**Issue by d3fstyle** [Openpanel-dev/openpanel#65]
Hi,
First thanks a lot for openpanel, this tool is really nice and easy to start with :)

I've doubts about identifying users using only the script tag, as when I don't identify them then in openpanel I see country,os and browser by default; but setting the username (as I only track logged in users) I lost all of that and see only username but can't find in documentation how to simply add the username and not override everything.

I set browser and os with `setGlobalProperties` but of course it doesn't show up in the fancy way openpanel renders it when I let the user unset.

```
window.op('ctor', {
      clientId: client_id,
      trackScreenViews: true,
      trackOutgoingLinks: true,
      trackAttributes: true,
});
window.op('setGlobalProperties',{
      browser: navigator.userAgent,
      os : navigator.platform,
});
window.op('identify', {
      profileId: "{{request.user.username}}",
      firstName: "{{request.user.username}}",
      email: "{{request.user.email}}",
});
```
![image](https://github.com/user-attachments/assets/674bda39-417f-4924-9975-b6a41ac1218b)

I'm using openpanel script tag within django templates.

**Comment by lindesvard** [comment]
Hey, this should not be the case 🤔 Identify should not override any of the other properties. 

Will try to reproduce this and get back to you! 

I assume you try to solve it with this, but this will have no effect (just a heads up)
```
window.op('setGlobalProperties',{
      browser: navigator.userAgent,
      os : navigator.platform,
});
```

**Comment by lindesvard** [comment]
Hopefully solved with this https://github.com/Openpanel-dev/openpanel/commit/0c93944d8a2eb9fc4a357349bb6cc2bb75e509dc

Thanks for reporting 🙏

**Comment by d3fstyle** [comment]
Thanks a lot! yes it's fixed. Now I removed setGlobalProperties, only set firstName and email and it appears just nice :)
![image](https://github.com/user-attachments/assets/9f105a11-54ac-489d-af40-f4ccb2f7b70f)
Thanks again.
