### ISSUE TITLE
Own user shows up twice under "Members"

### ISSUE THREAD

**Issue by perostlin** [Openpanel-dev/openpanel#66]
When looking at members I see myself twice.

![image](https://github.com/user-attachments/assets/b5cf66a8-8eec-4124-8e7f-1aad7d97ab2b)

**Comment by lindesvard** [comment]
Interesting! Will have a look!

**Comment by lindesvard** [comment]
Is the a invited user or the one created the organization? I see duplicate entires in the DB so want to understand how this happen

**Comment by iamjamesjohn** [comment]
I had 4 duplicated users, I deleted a project resulting in 0 projects in my org. I then went through the create project flow and afterwards there was a new duplicated user (now 5).

I believe it may be something to do with 
1. Creating a new project.
2. Creating the first project for an organisation.
3. Member not being deleted upon deleting project / deleting only project.

**Comment by lindesvard** [comment]
Should be fixed now. You'll still see duplicate entries but now you can delete them (if you're on a small screen you might need to scroll to the right to see the option)

Please re-open if you noticed any issues
