### ISSUE TITLE
IdentifyComponent cuases error and fails to track user

### ISSUE THREAD

**Issue by joncoronel** [Openpanel-dev/openpanel#67]
![image](https://github.com/user-attachments/assets/ed9e0066-118c-47e6-b5a9-6243fb60f56b)

Using OpenPanel with nextjs and tried adding the IdentifyComponent to a server component. 

`<IdentifyComponent
          profileId={profileId}
          firstName={firstName}
          lastName={lastName}
          email={email}
          properties={{
            tier: "free",
          }}
        />`
        
 It worked once or twice, but otherwise, it just prints this error in the browser console and the profile is not tracked.

**Comment by lindesvard** [comment]
Hmm, will investigate. 

What versions for next and openpanel are you using?

**Comment by joncoronel** [comment]
```
 "next": "^14.2.4",
"@openpanel/nextjs": "^1.0.3",
```

**Comment by lindesvard** [comment]
Are you sure you are using `<OpenPanelComponent />` as well? Because its required, otherwise `window.op` will not exists

**Comment by joncoronel** [comment]
Yep, have it at my root layout. I then use `<IdentifyComponent />` within a nested nav server component conditionally if the user is signed in.

**Comment by lindesvard** [comment]
1. Is `op.js` or `op1.js` loaded in network tab?
2. If you inspect the source code (in browser) can you find `window.op = window.op`?

**Comment by joncoronel** [comment]
Yes op1.js is loaded in the network tab and `window.op` is present in the browser source code. 
![image](https://github.com/user-attachments/assets/4ad69ed4-ec28-45b8-b9f1-f8daa03d22fc)

I believe I found the cause. I think the `<IdentifyComponent />` may be loading in too early. Before the op1.js file loads in. 

The placement of the `<IdentifyComponent />` is very strict. 
![image](https://github.com/user-attachments/assets/9996739a-c35c-4ee2-821b-0a91fd56f2f0)

In that image, the bottom `<IdentifyComponent />` works fine but the one above the `<OpenPanelComponent />` gives an error. 
It seems the `<IdentifyComponent />` has to be placed right after the `<OpenPanelComponent />` in the root layout. Otherwise, it will give the error.
