### ISSUE TITLE
Feature Request: Allow tracking events that happened in the past.

### ISSUE THREAD

**Issue by TaylorFacen** [Openpanel-dev/openpanel#69]
I run background jobs that might be delayed for various reasons. For example, although a user signs up at 10:30 AM, the background job to track the sign up and run downstream workflows might not run until 10:45 AM. If the user performs additional steps / page views after signing up, it could look like they viewed a page before signing up when they actually signed up before viewing a page.

Idea: An optional `timestamp` property when tracking events.

This is the **only** thing keeping me from OpenPanel so I would love to see it implemented.

**Comment by lindesvard** [comment]
Will try to solve this!

**Comment by lindesvard** [comment]
I have started to look at this (to keep you in the loop)

**Comment by TaylorFacen** [comment]
> I have started to look at this (to keep you in the loop)

Thanks! Let me know if you need me to test anything out.

**Comment by lindesvard** [comment]
I'm done with this but refactored related code quite a bit so want to do some thorough testing before merging this.

Here is the PR: https://github.com/Openpanel-dev/openpanel/pull/76

**Comment by TaylorFacen** [comment]
This is perfect. Thank you!

**Comment by lindesvard** [comment]
Merged it today!

**Comment by TaylorFacen** [comment]
I just realized that the nextjs sdk doesnt take a timestamp property. Any chance we can get that added in?

**Comment by lindesvard** [comment]
Just pass "__timestamp: isodate" as a property. On mobile now, sorry for bad example
