### ISSUE TITLE
How do "Conversions" work?

### ISSUE THREAD

**Issue by Than-DE** [Openpanel-dev/openpanel#71]
I am trying to set up conversions (e.g. after log in, how many start using feature X) and I would like to compare conversion rate between desktop and mobile users, for instance.

What are the steps to define a conversion?

![CleanShot 2024-10-09 at 09 20 10@2x](https://github.com/user-attachments/assets/f60c6b61-facb-47de-a331-59da029ef085)

**Comment by lindesvard** [comment]
This sounds more like a funnel imo or retention (in development right now). 

Conversions is a bad wording from my side this its just events that you have marked as "important".

<img width="537" alt="image" src="https://github.com/user-attachments/assets/04517d49-8837-4857-a7b4-6ffe488e92e4">

<img width="735" alt="image" src="https://github.com/user-attachments/assets/8d62fb81-1947-49a0-9fcc-aeb61fa7121b">

**Comment by Than-DE** [comment]
Ah ok now I understand what is meant with the Conversions tab. If you don't mind I might commit some documentation and a link in the empty state to make it a bit more clear. I can imagine this feature not being used a lot right now.

As for funnels, I think that is what I need at the moment. I would also like to compare funnels in some way if that's possible.

Is there a workaround right now to create some sort of funnel?

**Comment by lindesvard** [comment]
Oh, have you missed that :O Thats like the main feature of OpenPanel! Then I guess I need a much better way of showing explaining this. 

Any suggestions?

**Comment by Than-DE** [comment]
So, I think the reason I never looked into custom dashboards is because, at the moment, I am only interested in the base KPIs (unique visitors, stay duration etc.) and the events list.

I am coming directly from Mixpanel, so I am a lot familiar with their UI to create a report _outside of dashboards_. This way you can create reports ad hoc, and if you like it, you can always save it and put it in a dashboard. I think if this was possible, the custom reports would be used a bit more.

![CleanShot 2024-10-11 at 15 20 18@2x](https://github.com/user-attachments/assets/e04197e3-e1b1-49d7-b2d3-83655179425c)

---

Also, maybe a guided onboarding for new users would also be useful!

**Comment by lindesvard** [comment]
<img width="295" alt="image" src="https://github.com/user-attachments/assets/6895314c-1ab8-4e76-8cae-f087903faee6">

Coming!

**Comment by Than-DE** [comment]
Amazing! You should try to measure the difference in usage or track the adoption of this in general. I think its a useful change to learn from :)

**Comment by lindesvard** [comment]
Are you telling me to use OpenPanel to build OpenPanel ;)
