### ISSUE TITLE
How to retrieve `properties` values

### ISSUE THREAD

**Issue by jenpnd** [Openpanel-dev/openpanel#73]
In the Frontend, we have these `properties`: 
![image](https://github.com/user-attachments/assets/9356a481-dbfd-4273-bc2e-a0f6788f4231)

But when I am using the `export` endpoint, I am only getting these results, without `properties`:
`GET https://api.openpanel.dev/export/events?project_id=PROJECTID&event=EVENTNAME`

![image](https://github.com/user-attachments/assets/577163da-289a-451b-812b-0d870649859c)

Is there any endpoint I can use to get **all the events details** that I can find in the OpenPanel frontend?

**Comment by lindesvard** [comment]
Use the `includes` flag `GET http://api.openpanel.dev/export/events?includes=properties`

I'll release docs about the export api soon. But why I haven't is because I really want to redo how it is.
