### ISSUE TITLE
Auth Alternative

### ISSUE THREAD

**Issue by juandl** [Openpanel-dev/openpanel#79]
Why not use https://logto.io/ ? Its open source and support many things like mobile app and etc.

Clerk is quite annoying 😅

**Comment by lindesvard** [comment]
Never heard of it tbh.

But if I'll change it will be something that is integrated. So either it will be next-auth, lucia or custom implementation.

Auth is currently our only external dependency and would like to move away from it at some point. But for not it will stay

**Comment by artcups** [comment]
Thank you for a great service! We are looking into a selv hosted deployment. Would it be possible to byo auth idp in the future. We are hevely invested in Auth0 and rather not add a new idp into the mix, even though Clerk is really good.

**Comment by lindesvard** [comment]
Hey @artcups 

I have a working PR that will replace Clerk auth -> https://github.com/Openpanel-dev/openpanel/pull/103

We use https://github.com/pilcrowonpaper/arctic to connect to providers, and they have auth0. So it's possible to make this happen. I don't think I'll priorities this but PRs are always welcome. 

I'll keep this issue open so we can track it.

**Comment by lindesvard** [comment]
Now Clerk is removed atleast 🚀

**Comment by lindesvard** [comment]
Will close this actually
