### ISSUE TITLE
Unable to Set Redis `CONFIG` due to Cloud Provider Restrictions

### ISSUE THREAD

**Issue by Innei** [Openpanel-dev/openpanel#82]
#### Description:

We are facing an issue with Redis configuration in our cloud-managed Redis instance. As per the cloud provider's restrictions, **Redis `CONFIG` commands cannot be executed**. This limitation prevents us from manually editing or overriding the configuration settings.

#### Problem:
OpenPanel attempts to manually modify Redis configuration using the `CONFIG` command. However, in a cloud-managed Redis environment, this is not supported due to security and stability reasons imposed by the provider. As a result, the system is encountering failures when trying to apply the configuration.
![CleanShot 2024-10-25 at 1  59 42@2x](https://github.com/user-attachments/assets/990e0127-1cda-4c6f-b45c-0144294376d7)

#### Expected Behavior:
- The program should handle Redis configuration without relying on direct access to `CONFIG` commands.
- Ideally, OpenPanel should detect managed Redis environments and adapt its behavior accordingly, either by:
  - Relying on default configurations.
  - Using alternative methods allowed by the provider, such as environment variables or parameters available via the cloud provider’s interface.

#### Steps to Reproduce:
1. Deploy OpenPanel using a cloud-managed Redis instance (e.g., AWS Elasticache, GCP Memorystore, etc.).
2. Observe failures when the program attempts to run `CONFIG` commands.

#### Suggested Solution:
- Modify OpenPanel to avoid direct use of Redis `CONFIG` commands in environments where it is restricted.
- Implement conditional checks for cloud-managed Redis instances and utilize alternative configuration strategies.

#### Environment:
- Cloud Provider: GCP

**Comment by lindesvard** [comment]
Have wrapped it inside a try catch so it fails gracefully. Also mention it in the docs now
