### ISSUE TITLE
[feature request] setting global properties on OpenPanelComponent instead

### ISSUE THREAD

**Issue by leikoilja** [Openpanel-dev/openpanel#83]
Hey, @lindesvard. Once again, great project, thank you.  💪 

**Problem:**
Just came across that next.js sdk has a global properties setter as documented [here](https://docs.openpanel.dev/docs/sdks/nextjs#setting-global-properties). Great feature, but why is it on the client side using `useOpenPanel` hook?

**Proposed solution:**
Would it not be better to move setting of global properties in one place, in the root of the project, preferably on the server side. For next.js a good place would be `OpenPanelComponent` imho:
Example:
```tsx
      <OpenPanelComponent
        clientId="your-client-id"
        app_version: '1.0.2',
        environment: 'production',
      />
```

Or am i missing smth? :)

**Comment by lindesvard** [comment]
This is actually already supported. Just forgot to add it in the docs (https://docs.openpanel.dev/docs/sdks/nextjs#nextjs-options)

Example: 
```
<OpenPanelComponent globalProperties={{ app_version: '1.0.2', environment: 'production' }} />
```

> Worth pointing out, this is not reactive. These properties will be set once from this component

**Comment by leikoilja** [comment]
awesome, thanks @lindesvard 🙌
