### ISSUE TITLE
Emails - Invitations

### ISSUE THREAD

**Issue by juandl** [Openpanel-dev/openpanel#84]
I tried to invite members, but they never received an email, is required to set up any SMTP credentials or something? I have to use clerk invitation and then copy username on the database

**Comment by lindesvard** [comment]
Invites still needs some work on. One of either should happen

- If the invited user already has an account they should just get access (without any email)
- If the invited user does not have an account they should receive an email from Clerk that they have been invited.

If you self-host you might have missed some settings inside Clerk, not sure.

**Comment by lindesvard** [comment]
This is now fixed since we dont use Clerk anymore https://github.com/Openpanel-dev/openpanel/commit/d31d9924a58112a7599d7d8538a31764911a5b22
