### ISSUE TITLE
Tracking ecommerce sales with revenue

### ISSUE THREAD

**Issue by qx54** [Openpanel-dev/openpanel#85]
Does this project currently support tracking ecommerce sales, specifically including sales revenue?

If not, are there any plans to implement this feature?

**Comment by lindesvard** [comment]
Technically its supported. You can track what ever you want. 

So if you would do `track('purchase', { revenue: 100 }`. You would easily be able to get the total sum out in a report.

![image](https://github.com/user-attachments/assets/a67aef6d-bccb-4d2d-80c7-c113db9b376c)

You would just select what event (in this case `purchase` and then select `Sum of property` together with `Select property` (which would be `revenue`)

---

But I have plans to add "better" support for this and metrics on the overview as well but its will probably Q1 next year.

You can re-open this if you have more questions
