### ISSUE TITLE
Request for Docker compose file

### ISSUE THREAD

**Issue by joncoronel** [Openpanel-dev/openpanel#86]
Recently started using dokploy (similar to coolify) to manage and deploy apps on a vps. I was wondering if it was possible to get an example docker compose file to try to selfhost openpanel onto a vps that way it's easier to manage the container through dokploy. I tried it myself but couldn't get it to work correctly.

**Comment by lindesvard** [comment]
Use the docker-compose template we have in self-hosting folder https://github.com/Openpanel-dev/openpanel/blob/main/self-hosting/docker-compose.template.yml
