### ISSUE TITLE
can't access team account

### ISSUE THREAD

**Issue by johnalxndr** [Openpanel-dev/openpanel#92]
when I try logging into my account im consistently hitting a page:
"Not found The organization you were looking for could not be found."
![CleanShot 2024-11-20 at 08 16 23@2x](https://github.com/user-attachments/assets/588a7a2c-7c09-4a6e-b57e-5e9489592874)

console errors show ` failed: WebSocket is closed before the connection is established.`

**Comment by johnalxndr** [comment]
seems to be resolved now.. but couldn't login for a bout 10 min. just a heads up!

**Comment by lindesvard** [comment]
Removed some legacy code which caused this issue. Sorry 🥹
