### ISSUE TITLE
How to track pageView/screenView via API

### ISSUE THREAD

**Issue by cedricatoutliant** [Openpanel-dev/openpanel#97]
I found out that there are options in the client JS libs to track screenViews but none to track them via an API call.
I need it to track visits through rudderstack. Here's my request:

```javascript
if (event.type == 'page') {
    return {
      header: {
        'x-client-ip': event.request_ip
      },
      "type": "screen_view",
      '__path': event.context?.page?.path,
      "payload": {
        '__path': event.context?.page?.path,
        "profileId": event.userId
      }
    }
  }```

Thanks.

**Comment by lindesvard** [comment]
Yes, almost there 😂 

You need to pass a valid (and hopefully the users user-agent) user-agent. We use the user-agent to determine if its a server or client event.

We also use the user-agent to get information as device and such. So if you pass down the user agent from the user it will probably start working.
