### ISSUE TITLE
Linear and Area seems to be the same?

### ISSUE THREAD

**Issue by holgersindbaek** [Openpanel-dev/openpanel#98]
I'm testing out Openpanel.

From what I can see "Area" and "Linear" seems to be the same? Shouldn't "Area" stack the values?

<img width="1004" alt="Screenshot 2024-11-26 at 16 42 46" src="https://github.com/user-attachments/assets/9274034d-fc11-4767-b453-4ad9f6e29f7d">

<img width="1008" alt="Screenshot 2024-11-26 at 16 42 52" src="https://github.com/user-attachments/assets/db2e4700-ba15-4820-9ef5-6f46b1d075e3">

**Comment by lindesvard** [comment]
Will fix this for sure!

**Comment by holgersindbaek** [comment]
Awesome. Thanks.

I'm thinking about switching from Mixpanel. Either partly or completely. I'm hoping to self-host, but I still have to set that up. I didn't manage to do it myself through with Digital Ocean, but I've been talking with the guy from Ptah and once he updates his script I should be able to do it through that: https://ptah.sh/marketplace/analytics/openpanel/. 

Keep up the good work!

**Comment by lindesvard** [comment]
This https://github.com/Openpanel-dev/openpanel/commit/82d438164e9fd49a7c1b6443498dd19a84341725 should fix it. Deploying now.

Glad you like it :) What problems did you have with setting it up? Would love to know more. Join the discord and ping me pls

Closing this
